### ISSUE TITLE
Make `--timeout` use seconds

### ISSUE THREAD

**Issue by smoelius** [trailofbits/test-fuzz#208]
```
      --timeout <TIMEOUT>     Number of milliseconds to consider a hang when fuzzing or replaying
                              (equivalent to -- -t <TIMEOUT> when fuzzing)
```
AFLplusplus's `-V` option uses seconds, as do [libfuzzer](https://llvm.org/docs/LibFuzzer.html)'s `--timeout` and `--max_total_time` options, and it's hard to keep the distinction.

Also, the extra granularity probably isn't necessary.

**Comment by dhruvdabhi101** [comment]
Hello, I am rust beginner. And I think I found the change i need to make to fix this issue. So can you please assign this issue to me ?

I have to just change 
```diff
- Duration::from_millies 
+ Duration::from_secs
```
and also some changes where i need to change from 1000 to 1 because of conversion from millisecs to secs. 
![Screenshot 2023-05-24 at 16 35 28](https://github.com/trailofbits/test-fuzz/assets/91935072/ad98d215-f54f-4349-ad48-9a07c0f5bb36)

**Comment by smoelius** [comment]
@dhruvdabhi101 Thanks very much for your interest. I've assigned the issue to you.

One other location that I want to call out as needing to change is this one: https://github.com/trailofbits/test-fuzz/blob/49843b3a9fdc8c800af7b31036ac33efcb7ee068/cargo-test-fuzz/src/lib.rs#L945

Incidentally, I think there is a bug there. 😬 `afl-fuzz` expects its `-t` argument to be in milliseconds, not nanos:
```
  -t msec       - timeout for each run (auto-scaled, default 1000 ms). Add a '+'
```
So I think that line should probably be:
```rust
 args.extend(["-t".to_owned(), format!("{}", timeout)]); 
```
But following your changes, it will be something like:
```rust
 args.extend(["-t".to_owned(), format!("{}", timeout * MILLIS_PER_SEC)]); 
```
