### ISSUE TITLE
support traits in impls

### ISSUE THREAD

**Issue by incertia** [trailofbits/test-fuzz#24]
`test_fuzz_impl` fails to correctly extract `T: Trait` from `impl <T: Trait> Struct<T>` and apply it to `Args` when fuzzing the impl functions. See daf5440 for some basic work trying to address this.

**Comment by smoelius** [comment]
This is starting to come back to me now.

Not putting the traits in `Args` was intentional because doing so can cause `serde_derive` to fail in some cases. (Related: https://github.com/rust-lang/rust-clippy/issues/1689, https://github.com/rust-lang/api-guidelines/issues/6)

But as recent experience shows, it's needed in some cases.

So I'm wondering what the best way to handle this is. A macro option to include the traits in `Args`?

**Comment by smoelius** [comment]
For syntax, I'm leaning toward something like:
```
#[test_fuzz(bound("T"))]
```
